### ISSUE TITLE
Initial review needed

### ISSUE THREAD

**Issue by kcho** [AMP-SCZ/dpanonymize#2]
@tashrifbillah Initial review is needed on the framework before moving towards  to pii removal module for each datatype.

I've designed `dpanonymize` to be called from `sync.py` from `lochness`, which is closer to what we want, but also provided `dpanon.py` for us in case we need this later.

Currently, pii removal for different datatypes are just "copy" function, where files are copied from PROTECTED to GENERAL and it takes both BIDS and non-BIDS pheonix structure (requires user input if it's BIDS or not)

**Comment by tashrifbillah** [comment]
Tashrif has reviewed the following aspects:

* testing infrastructure
* usage commands from README
  * file-based anonymization seems to work fine 👍 
  * directory-based anonymization may work 🚶 
  * phoniex-root-based anonymization is broken 👎 
* `dpanon.py code`
* `dpanonymize/__init__.py` code

TODO
* Modules in dpanonymize should be tested/reviewed once done

**Comment by tashrifbillah** [comment]
> file-based anonymization seems to work fine 👍
directory-based anonymization may work 🚶
phoniex-root-based anonymization is broken 👎

All of them are functional now.
