### ISSUE TITLE
TypeError: cannot unpack non-iterable Namespace object

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpanonymize#7]
```
(dpanonymize) [tb571@rc-predict-lochness AD00451]$ pwd
/data/predict/tb571_lochness_test/RED-PHOENIX/PROTECTED/FAKE/raw/surveys/AD00451

(dpanonymize) [tb571@rc-predict-lochness AD00451]$ dpanon.py -dt survey -i AD00451.FAKE.json -o de.json
Traceback (most recent call last):
  File "/home/tb571/miniconda3/envs/dpanonymize/bin/dpanon.py", line 95, in <module>
    parser, args = parse_args(sys.argv[1:])
TypeError: cannot unpack non-iterable Namespace object
```

**Comment by tashrifbillah** [comment]
Programs involving argparse is written like [this](https://github.com/pnlbwh/TBSS/blob/master/lib/tbss_all#L155). All arguments are part of `main()` function. Accordingly, all your arguments should be inside `dpanonymize()` function.

**Comment by tashrifbillah** [comment]
The above commit is a quick fix but I shall standardize `dpanon.py` according to my last comment.

**Comment by kcho** [comment]
Thanks for spotting this. Fixed here https://github.com/AMP-SCZ/dpanonymize/commit/861f18becdeed3dabca51b471b1fd7d6f219ae52

**Comment by tashrifbillah** [comment]
I think I'll co-author that commit 🤪
