### ISSUE TITLE
Put datatype as choices

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpanonymize#8]
[This](https://github.com/AMP-SCZ/dpanonymize/blob/master/scripts/dpanon.py#L25) should be put as choices [here](https://github.com/AMP-SCZ/dpanonymize/blob/master/scripts/dpanon.py#L67) like [this](https://github.com/pnlbwh/luigi-pnlpipe/blob/hcp/workflows/ExecuteTask.py#L56)

**Comment by kcho** [comment]
Does [this](https://github.com/pnlbwh/luigi-pnlpipe/blob/hcp/workflows/ExecuteTask.py#L56) allow `-dt` to be not given by the user? The current [`lock_phoenix`  ](https://github.com/AMP-SCZ/dpanonymize/blob/7928e687e649ae1fcf9e7e1c44530a97a2cb5c9d/dpanonymize/__init__.py#L116-L118) runs `PII_removal` on all datatypes, if `datatype` is not specified from the user through `argparse`.

**Comment by tashrifbillah** [comment]
> Does this allow -dt to be not given by the user?

Yes it does. The purpose of choices is to prevent spelling mistakes in arguments when provided e.g. `survey` vs `surveys`.

**Comment by tashrifbillah** [comment]
PR #12
